name = "SocialIdentity"
uuid = "c0a3a5f3-4b1e-4e3d-8b7a-2d9c6e1f0a5b"
version = "0.1.0"
authors = ["Fjalar J. de Haan <fjalar.dehaan@unimelb.edu.au>"]

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Graphs = "1"
LinearAlgebra = "1.12.0"
MetaGraphsNext = "0.7"
Printf = "1.11.0"
Random = "1.11.0"
StaticArrays = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
